Module4 task1
htmlacademy-react/1506667-six-cities-9 pull request #5
Opened 2022-02-22 21:22 UTC by rook-a

2022-02-22 21:26 UTC, rook-a commented on project/src/components/places-list/places-list.tsx
> +  };
вот тут основные проблемы. evt тип я не смог правильно определить и offerId линтер не видит.

и в целом реализация под вопросом. так делать ок ?

2022-02-23 10:52 UTC, Finnko requested changes

2022-02-23 10:52 UTC, Finnko commented on project/src/components/boormark/boormark.tsx
> +  let [value, setValue] = useState(isFavorite);
```suggestion
  const [value, setValue] = useState(isFavorite);
```
Но вообще это надо удалить

2022-02-23 10:52 UTC, Finnko commented on project/src/components/boormark/boormark.tsx
> +    text: value ? 'In bookmarks' : 'To bookmarks',
Мне не нравится) Объясню почему. Состояние isFavorite будет приходить у оффера с сервера, нет нужды хранить его локально еще в компоненте. Раз оно приходит пропсом в этот компонент, то текст можно прямо по месту по условию вывести, активный класс накинуть через classnames. Сам же класс прокидывать внешним пропсом в зависимости от места использования и мержить опять же через cn вместе с активным классом. Таким образом я бы сделал пропсы у компонента isSmall, className и isFavorite

2022-02-23 10:52 UTC, Finnko commented on project/src/components/boormark/boormark.tsx
> +        setValue((value = !value));
Оно работает? Мне кажется ты упустил, в функции сеттере состояния у нас или новое состояние или функция коллбек устанавливающая это состояние. У тебя что-то между. Ну и в целом это здесь не нужно (см выше)

2022-02-23 10:52 UTC, Finnko commented on project/src/components/card-place/card-place.tsx
> +    <article className="cities__place-card place-card" id={`${id}`}>
Айди здесь не нужен, тебе надо из списка (родительского компонента) прокинуть сюда коллбек чтобы в момент наведения получить нужный айди. Подробнее https://ru.reactjs.org/docs/lifting-state-up.html

2022-02-23 10:52 UTC, Finnko commented on project/src/components/card-place/card-place.tsx
> +            <span style={{ width: `${ratingPercent(rating)}%` }}></span>
Нет глагола в нейминге функции расчета процентов.

2022-02-23 10:52 UTC, Finnko commented on project/src/components/card-place/card-place.tsx
> +        <p className="place-card__type">{type}</p>
В верстке тип апартов с большой буквы

2022-02-23 10:52 UTC, Finnko commented on project/src/components/places-list/places-list.tsx
> +  let [offerId, setOfferId] = useState('');
Начальное состояние null. Тип или number или null
```suggestion
  const [offerId, setOfferId] = useState<number | null>(null);
```

2022-02-23 10:52 UTC, Finnko commented on project/src/components/places-list/places-list.tsx
> +  };
Нет так не подойдет. Посмотри ссылку на доку реакта с подъемом состояния. Тебе надо прокинуть вниз в ребенка коллбек который сработает на наведении и прокинет в родителя id. В реакте за счет встроенных оптимизаций большого выигрыша от делегирования ты не получишь. Если надо есть пруф на исследование с 1000 элементами (что в реальной жизни никогда не будет, потому что есть библиотеки по типу react-virtualized которые помогают рендерить что во вьюпорте и недалеко от него)

2022-02-23 10:52 UTC, Finnko commented on project/src/components/places-list/places-list.tsx
> +    <div onMouseOver={mouseEvent} className={`places__list ${className}`}>
Переместить коллбек вниз на ребенка

2022-02-23 10:52 UTC, Finnko commented on project/src/pages/property/property.tsx
> +  const offersNearby = offers.slice(0, 3);
3 в константу

2022-02-23 10:52 UTC, Finnko commented on project/src/types/offer.ts
> +  };
Я бы выделил city в отдельный интерфейс

2022-02-23 10:52 UTC, Finnko commented on project/src/types/offer.ts
> +  };
host тоже

2022-02-23 10:52 UTC, Finnko commented on project/src/types/offer.ts
> +  };
location

2022-02-23 10:52 UTC, Finnko commented on project/src/types/review.ts
> +  };
user

2022-02-26 08:45 UTC, Finnko approved these changes

2022-02-26 08:45 UTC, merged